### ISSUE TITLE
Service not getting detected in Android.

### ISSUE THREAD

**Issue by mizzb** [Nimrodda/flutter_nsd#1]
I checked out the example project and changed the service name to '_http._tcp' which i am running locally.
The IOs detects it but not in Android.

**Comment by Nimrodda** [comment]
try to add a `.` at the end and see if it fixes it: `_http._tcp.`

**Comment by mizzb** [comment]
Tried. still not working

**Comment by mizzb** [comment]
Issue is only in Android emulator.
Tried connecting device its working fine. !!

**Comment by Nimrodda** [comment]
Glad to hear it works 👍  
I should probably mention that Android emulator doesn't work in the README file.
How was the setup for iOS, any steps which I forgot to mention?

**Comment by mizzb** [comment]
@Nimrodda : no issues..  iOs app works fine in Simulator.
thanks for the support
