### ISSUE TITLE
Make pubspec description valid

### ISSUE THREAD

**Issue by egaga** [Nimrodda/flutter_nsd#10]
This is very minor and doesn't concern me, but better to be valid than not.
I didn't make a pull request because probably you know better what you like to have.

![image](https://user-images.githubusercontent.com/138295/126466515-46c67ca7-1885-4ce2-ae21-a872d15bf528.png)

From: https://pub.dev/packages/flutter_nsd/score

**Comment by Nimrodda** [comment]
Thanks for the tip. I'll look into it 👍

**Comment by Nimrodda** [comment]
Fixed in 1.3.0
