### ISSUE TITLE
Notify when service is lost

### ISSUE THREAD

**Issue by Nimrodda** [Nimrodda/flutter_nsd#28]
Right now the plugin sends events of services appearing, but no events when they disappear.
According to my brief investigation, Android, iOS and MacOS support this, but Windows which uses the MDNS library requires further investigation.

@jnstahl Do you happen to know if MDNS supports [this](https://developer.android.com/reference/android/net/nsd/NsdManager.DiscoveryListener#onServiceLost(android.net.nsd.NsdServiceInfo))?

**Comment by jnstahl** [comment]
At the core, MDNS sends a broadcast out, in essence "who supports _http._tcp." and all the devices who do will send a reply.
The only way to tell if a service has gone away is to continuously broadcast, keep a database of known responses and then compare if a service that was there before no longer responds.

For iOS and Android, this is something the OS keeps track of internally, presumably the OS will periodically broadcast regardless if any query is open, and the API only allows you to get a notification of the internal database.

Emulating the same behavior on windows would probably be excessive, as here the broadcasting is done by the app directly, not by the OS. And, it would also be non-trivial to keep track of things as possibly not each device will respond every single time, so one would have to have an algorithm tracking additions and removals.

**Comment by jnstahl** [comment]
I guess it all depends on what the use case is here. If an app wants to monitor what is available in the network continuously, the removal notification is essential. I would think that most apps will use the flutter_nsd package just to connect to something (lets say a printer), then be done with it. At least that is how I use it.

**Comment by Nimrodda** [comment]
Yeah, it's the same use case I have. In my case I don't even list the available devices if there's only one, but just connect to it directly. I came up with this after addressing #27. I realized we have the API in place, but it's actually not used :sweat_smile: 
I see you already created a PR for this. Great stuff! Thanks once again for such swift action :muscle:

**Comment by jnstahl** [comment]
why is this issue re-opened? any issues with my fix?

**Comment by Nimrodda** [comment]
I don't remember. Probably a mistake.
