### ISSUE TITLE
NsdServiceInfo Class should have IP

### ISSUE THREAD

**Issue by casterock** [Nimrodda/flutter_nsd#39]
NsdServiceInfo Class only shows: hostname, port, name and txt. Should have resolved IP

**Comment by Nimrodda** [comment]
Please see my [comment](https://github.com/Nimrodda/flutter_nsd/issues/38#issuecomment-1167150962) and let me know if it fixes also this issue.

**Comment by casterock** [comment]
Not really realice how to show IP, NsdServiceInfo Class didn't have IP attribute

/// Info class for holding discovered service
class NsdServiceInfo {
  final String? hostname;
  final int? port;
  final String? name;
  final Map<String, Uint8List>? txt;

  NsdServiceInfo(this.hostname, this.port, this.name, this.txt);
}

**Comment by Nimrodda** [comment]
Yes, this is known behavior currently. `hostname` can either be IP or hostname. There's a separate ticket for it #22.
