### ISSUE TITLE
missing permission for some Android versions

### ISSUE THREAD

**Issue by jnstahl** [Nimrodda/flutter_nsd#45]
Discovery fails on some Android builds due to missing NEARBY_DEVICES permission in the manifest:

 <uses-permission android:name="android.permission.NEARBY_DEVICES" />

An easy workaround is to add this permission into the manifest of the app that uses the package

**Comment by Nimrodda** [comment]
Thanks for reporting this. A PR with this update would be appreciated :)

**Comment by jnstahl** [comment]
yes when I get to it - for now I just wanted to document it.
