### ISSUE TITLE
stopDiscovery Not working giving below exception 

### ISSUE THREAD

**Issue by harishkthedeveloper** [Nimrodda/flutter_nsd#47]
NsdError (message: "stopDiscovery: MulticastLock under-locked nsdMulticastLock", cause: internalError)

NsdError (message: "stopDiscovery: MulticastLock under-locked nsdMulticastLock", cause: internalError)
I/flutter ( 2026): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 2026): │ #0   MethodChannelNsdPlatform.invoke.<anonymous closure> (package:nsd_platform_interface/src/method_channel_nsd_platform.dart:201:28)
I/flutter ( 2026): │ #1   _rootRunUnary (dart:async/zone.dart:1434:47)
I/flutter ( 2026): │ #2   _CustomZone.runUnary (dart:async/zone.dart:1335:19)
I/flutter ( 2026): │ #3   _FutureListener.handleError (dart:async/future_impl.dart:177:22)
I/flutter ( 2026): │ #4   Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
I/flutter ( 2026): │ #5   Future._propagateToListeners (dart:async/future_impl.dart:799:13)
I/flutter ( 2026): │ #6   Future._completeError (dart:async/future_impl.dart:609:5)
I/flutter ( 2026): │ #7   _completeOnAsyncError (dart:async-patch/async_patch.dart:272:13)
I/flutter ( 2026): │ #8   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
I/flutter ( 2026): │ #9   <asynchronous suspension>
I/flutter ( 2026): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 2026): │ 12:05:02.933 (+0:00:46.781794)
I/flutter ( 2026): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 2026): │ ⛔ ERROR OCCURS NsdError (message: "stopDiscovery: MulticastLock under-locked nsdMulticastLock", cause: internalError)

**Comment by Nimrodda** [comment]
Do you have a sample project that reproduces this issue? Can you reproduce the issue with the example project that comes with the plugin? I need more info

**Comment by harishkthedeveloper** [comment]
@Nimrodda Thank you for your response. I've created a custom demo project for you to review:

Clone link - [https://github.com/harishkthedeveloper/mdns_demo.git](https://github.com/harishkthedeveloper/mdns_demo.git)

I've also provided a demo video and log file for your convenience:

Demo video & log file - [https://drive.google.com/drive/folders/1cQdpHMdnf3s-ofJ8kjixmOHL55P3AbO8?usp=sharing](https://drive.google.com/drive/folders/1cQdpHMdnf3s-ofJ8kjixmOHL55P3AbO8?usp=sharing)

To reproduce the issue, please follow these steps:

**NOTE**: In the file `nsd_service.dart`, replace `String serviceTypeDiscover = "<add_your_service>._tcp";` with your service name.

1. Click on the "Scan" button to go to the scanned device list page.
2. Then, click the back button on the Appbar (we are stopping the service in the Dispose method).
3. Try to switch between Wi-Fi networks in your mobile settings and return to the app.
4. Repeat the above three steps more than 10 times to encounter the following errors:

**Errors**:
```
[MDNS] ERROR: ID:- 4961d42f-eed2-4952-89c9-9e9fad13c746 NsdError (message: "stopDiscovery: MulticastLock under-locked nsdMulticastLock", cause: internalError)

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NsdError (message: "Maximum outstanding requests reached", cause: maxLimit)
```

I'm seeking your guidance on why the service is not getting stopped or closed, and how we can avoid these errors. If these errors persist, it becomes challenging to provide users with a new device list. Your insights and suggestions will be highly appreciated.

**Comment by Nimrodda** [comment]
I noticed you're mixing `flutter_nsd` plugin with `nsd` plugin and the file you referred me to `nsd_service.dart` doesn't even use `flutter_nsd`'s API. You should file this bug to `nsd` plugin repo.

**Comment by harishkthedeveloper** [comment]
@Nimrodda thank you for your response, certainly i will check it with nsd, let me first try with only flutter_nsd plugin. I will let you know on further updates here if i get the solution
