### ISSUE TITLE
Invalid README.md example

### ISSUE THREAD

**Issue by pheki** [Nimrodda/flutter_nsd#5]
It looks like the example in the README.md getting started has been committed mid-changes:

It does not actually handle actual services (the `onData` argument is unused), but uses `onError` as if it was `onData`. 

I suppose it was supposed to use `onError` like in the [example](https://github.com/Nimrodda/flutter_nsd/blob/2a7a233bf45a5dadf2d3036c2f62dc35bc25463e/example/lib/main.dart)

**Comment by Nimrodda** [comment]
You're right, it was indeed half done. It's fixed now. Thanks for reporting 👍
