### ISSUE TITLE
Add support for informing about disappearing services

### ISSUE THREAD

**Issue by egaga** [Nimrodda/flutter_nsd#9]
Have you thought about adding support for notifying about losing a service? I would think it's quite a relevant functionality to me.

I think the related APIs platform-wise are these:

Android: https://developer.android.com/reference/android/net/nsd/NsdManager.DiscoveryListener#onServiceLost(android.net.nsd.Nsd
ServiceInfo)
ios: https://developer.apple.com/documentation/foundation/netservicebrowserdelegate/1412917-netservicebrowser

**Comment by egaga** [comment]
Perhaps this might have only limited value because one shouldn't be having the listener open for long time due to battery usage.
So the disconnection services won't be 100% catched anyways if the listener is not active all the time.

**Comment by Nimrodda** [comment]
Yeah, that's true. I've also been thinking how to fit this feature to the current API since currently services are emitted as they're discovered. It would most probably require adding a field to `NsdServiceInfo` to indicate if it's active or not, or something like that.
